[project]
name = "NLIIS2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pip>=25.1.1",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "spacy>=3.8.5",
    "sqlalchemy>=2.0.40",
]
