[project]
name = "lab3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "natasha>=1.6.0",
    "pypandoc>=1.15",
    "setuptools>=80.3.1",
    "stop-words>=2018.7.23",
    "textract>=1.6.5",
    "tk>=0.1.0",
]
